#############################################################################
# Makefile for building: ConlangDictionary
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Aug 15 14:18:13 2015
# Project:  ConlangDictionary.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile ConlangDictionary.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtSql -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cdicdatabase.cc \
		choosephonemesdialog.cc \
		dictionary.cc \
		earleyparser.cc \
		editablequerymodel.cc \
		editphonologydialog.cc \
		featurebundlesdialog.cc \
		main.cc \
		mainwindow.cc \
		managefeaturesdialog.cc \
		morphemeupdatedialog.cc \
		phonologypage.cc \
		phonotacticspage.cc \
		suprasegmentalspage.cc \
		wordpage.cc moc_choosephonemesdialog.cpp \
		moc_dictionary.cpp \
		moc_editablequerymodel.cpp \
		moc_editphonologydialog.cpp \
		moc_featurebundlesdialog.cpp \
		moc_mainwindow.cpp \
		moc_managefeaturesdialog.cpp \
		moc_morphemeupdatedialog.cpp \
		moc_phonologypage.cpp \
		moc_phonotacticspage.cpp \
		moc_suprasegmentalspage.cpp \
		moc_wordpage.cpp
OBJECTS       = cdicdatabase.o \
		choosephonemesdialog.o \
		dictionary.o \
		earleyparser.o \
		editablequerymodel.o \
		editphonologydialog.o \
		featurebundlesdialog.o \
		main.o \
		mainwindow.o \
		managefeaturesdialog.o \
		morphemeupdatedialog.o \
		phonologypage.o \
		phonotacticspage.o \
		suprasegmentalspage.o \
		wordpage.o \
		moc_choosephonemesdialog.o \
		moc_dictionary.o \
		moc_editablequerymodel.o \
		moc_editphonologydialog.o \
		moc_featurebundlesdialog.o \
		moc_mainwindow.o \
		moc_managefeaturesdialog.o \
		moc_morphemeupdatedialog.o \
		moc_phonologypage.o \
		moc_phonotacticspage.o \
		moc_suprasegmentalspage.o \
		moc_wordpage.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ConlangDictionary.pro
QMAKE_TARGET  = ConlangDictionary
DESTDIR       = 
TARGET        = ConlangDictionary

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ConlangDictionary.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtSql.prl \
		/usr/lib/i386-linux-gnu/libQtXml.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile ConlangDictionary.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtSql.prl:
/usr/lib/i386-linux-gnu/libQtXml.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ConlangDictionary.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ConlangDictionary1.0.0 || $(MKDIR) .tmp/ConlangDictionary1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ConlangDictionary1.0.0/ && $(COPY_FILE) --parents cdicdatabase.h choosephonemesdialog.h const.h dictionary.h earleyparser.h editablequerymodel.h editphonologydialog.h featurebundlesdialog.h mainwindow.h managefeaturesdialog.h morphemeupdatedialog.h phonologypage.h phonotacticspage.h suprasegmentalspage.h wordpage.h .tmp/ConlangDictionary1.0.0/ && $(COPY_FILE) --parents cdicdatabase.cc choosephonemesdialog.cc dictionary.cc earleyparser.cc editablequerymodel.cc editphonologydialog.cc featurebundlesdialog.cc main.cc mainwindow.cc managefeaturesdialog.cc morphemeupdatedialog.cc phonologypage.cc phonotacticspage.cc suprasegmentalspage.cc wordpage.cc .tmp/ConlangDictionary1.0.0/ && (cd `dirname .tmp/ConlangDictionary1.0.0` && $(TAR) ConlangDictionary1.0.0.tar ConlangDictionary1.0.0 && $(COMPRESS) ConlangDictionary1.0.0.tar) && $(MOVE) `dirname .tmp/ConlangDictionary1.0.0`/ConlangDictionary1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ConlangDictionary1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_choosephonemesdialog.cpp moc_dictionary.cpp moc_editablequerymodel.cpp moc_editphonologydialog.cpp moc_featurebundlesdialog.cpp moc_mainwindow.cpp moc_managefeaturesdialog.cpp moc_morphemeupdatedialog.cpp moc_phonologypage.cpp moc_phonotacticspage.cpp moc_suprasegmentalspage.cpp moc_wordpage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_choosephonemesdialog.cpp moc_dictionary.cpp moc_editablequerymodel.cpp moc_editphonologydialog.cpp moc_featurebundlesdialog.cpp moc_mainwindow.cpp moc_managefeaturesdialog.cpp moc_morphemeupdatedialog.cpp moc_phonologypage.cpp moc_phonotacticspage.cpp moc_suprasegmentalspage.cpp moc_wordpage.cpp
moc_choosephonemesdialog.cpp: cdicdatabase.h \
		const.h \
		earleyparser.h \
		choosephonemesdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) choosephonemesdialog.h -o moc_choosephonemesdialog.cpp

moc_dictionary.cpp: cdicdatabase.h \
		const.h \
		earleyparser.h \
		dictionary.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dictionary.h -o moc_dictionary.cpp

moc_editablequerymodel.cpp: editablequerymodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editablequerymodel.h -o moc_editablequerymodel.cpp

moc_editphonologydialog.cpp: const.h \
		cdicdatabase.h \
		earleyparser.h \
		editphonologydialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editphonologydialog.h -o moc_editphonologydialog.cpp

moc_featurebundlesdialog.cpp: cdicdatabase.h \
		const.h \
		earleyparser.h \
		featurebundlesdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) featurebundlesdialog.h -o moc_featurebundlesdialog.cpp

moc_mainwindow.cpp: dictionary.h \
		cdicdatabase.h \
		const.h \
		earleyparser.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_managefeaturesdialog.cpp: cdicdatabase.h \
		const.h \
		earleyparser.h \
		managefeaturesdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) managefeaturesdialog.h -o moc_managefeaturesdialog.cpp

moc_morphemeupdatedialog.cpp: morphemeupdatedialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) morphemeupdatedialog.h -o moc_morphemeupdatedialog.cpp

moc_phonologypage.cpp: cdicdatabase.h \
		const.h \
		earleyparser.h \
		phonologypage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) phonologypage.h -o moc_phonologypage.cpp

moc_phonotacticspage.cpp: cdicdatabase.h \
		const.h \
		earleyparser.h \
		phonotacticspage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) phonotacticspage.h -o moc_phonotacticspage.cpp

moc_suprasegmentalspage.cpp: cdicdatabase.h \
		const.h \
		earleyparser.h \
		suprasegmentalspage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) suprasegmentalspage.h -o moc_suprasegmentalspage.cpp

moc_wordpage.cpp: cdicdatabase.h \
		const.h \
		earleyparser.h \
		wordpage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wordpage.h -o moc_wordpage.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

cdicdatabase.o: cdicdatabase.cc cdicdatabase.h \
		const.h \
		earleyparser.h \
		mainwindow.h \
		dictionary.h \
		editablequerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cdicdatabase.o cdicdatabase.cc

choosephonemesdialog.o: choosephonemesdialog.cc choosephonemesdialog.h \
		cdicdatabase.h \
		const.h \
		earleyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o choosephonemesdialog.o choosephonemesdialog.cc

dictionary.o: dictionary.cc const.h \
		dictionary.h \
		cdicdatabase.h \
		earleyparser.h \
		mainwindow.h \
		phonologypage.h \
		phonotacticspage.h \
		suprasegmentalspage.h \
		wordpage.h \
		morphemeupdatedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dictionary.o dictionary.cc

earleyparser.o: earleyparser.cc earleyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o earleyparser.o earleyparser.cc

editablequerymodel.o: editablequerymodel.cc editablequerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editablequerymodel.o editablequerymodel.cc

editphonologydialog.o: editphonologydialog.cc editphonologydialog.h \
		const.h \
		cdicdatabase.h \
		earleyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editphonologydialog.o editphonologydialog.cc

featurebundlesdialog.o: featurebundlesdialog.cc const.h \
		editablequerymodel.h \
		featurebundlesdialog.h \
		cdicdatabase.h \
		earleyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o featurebundlesdialog.o featurebundlesdialog.cc

main.o: main.cc mainwindow.h \
		dictionary.h \
		cdicdatabase.h \
		const.h \
		earleyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

mainwindow.o: mainwindow.cc mainwindow.h \
		dictionary.h \
		cdicdatabase.h \
		const.h \
		earleyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cc

managefeaturesdialog.o: managefeaturesdialog.cc const.h \
		managefeaturesdialog.h \
		cdicdatabase.h \
		earleyparser.h \
		editablequerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o managefeaturesdialog.o managefeaturesdialog.cc

morphemeupdatedialog.o: morphemeupdatedialog.cc morphemeupdatedialog.h \
		cdicdatabase.h \
		const.h \
		earleyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o morphemeupdatedialog.o morphemeupdatedialog.cc

phonologypage.o: phonologypage.cc const.h \
		phonologypage.h \
		cdicdatabase.h \
		earleyparser.h \
		editablequerymodel.h \
		managefeaturesdialog.h \
		featurebundlesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phonologypage.o phonologypage.cc

phonotacticspage.o: phonotacticspage.cc const.h \
		phonotacticspage.h \
		cdicdatabase.h \
		earleyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phonotacticspage.o phonotacticspage.cc

suprasegmentalspage.o: suprasegmentalspage.cc const.h \
		suprasegmentalspage.h \
		cdicdatabase.h \
		earleyparser.h \
		choosephonemesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o suprasegmentalspage.o suprasegmentalspage.cc

wordpage.o: wordpage.cc const.h \
		wordpage.h \
		cdicdatabase.h \
		earleyparser.h \
		managefeaturesdialog.h \
		featurebundlesdialog.h \
		editphonologydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wordpage.o wordpage.cc

moc_choosephonemesdialog.o: moc_choosephonemesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_choosephonemesdialog.o moc_choosephonemesdialog.cpp

moc_dictionary.o: moc_dictionary.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dictionary.o moc_dictionary.cpp

moc_editablequerymodel.o: moc_editablequerymodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editablequerymodel.o moc_editablequerymodel.cpp

moc_editphonologydialog.o: moc_editphonologydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editphonologydialog.o moc_editphonologydialog.cpp

moc_featurebundlesdialog.o: moc_featurebundlesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_featurebundlesdialog.o moc_featurebundlesdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_managefeaturesdialog.o: moc_managefeaturesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_managefeaturesdialog.o moc_managefeaturesdialog.cpp

moc_morphemeupdatedialog.o: moc_morphemeupdatedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_morphemeupdatedialog.o moc_morphemeupdatedialog.cpp

moc_phonologypage.o: moc_phonologypage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_phonologypage.o moc_phonologypage.cpp

moc_phonotacticspage.o: moc_phonotacticspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_phonotacticspage.o moc_phonotacticspage.cpp

moc_suprasegmentalspage.o: moc_suprasegmentalspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_suprasegmentalspage.o moc_suprasegmentalspage.cpp

moc_wordpage.o: moc_wordpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wordpage.o moc_wordpage.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

